name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar

      - name: Deploy to WSL (via SSH)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WSL_HOST }}
          username: ${{ secrets.WSL_USER }}
          key: ${{ secrets.WSL_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/${{ secrets.WSL_USER }}/app"

      - name: Restart WSL App Service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WSL_HOST }}
          username: ${{ secrets.WSL_USER }}
          key: ${{ secrets.WSL_SSH_KEY }}
          script: |
            sudo systemctl restart myapp.service
